#!/usr/bin/env python3
"""
This  module imports async_generator from previous task then writes caroutine
called async_comprehension
"""

from typing import List
import asyncio
async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    This is the async comprehension method that returns a list of 10 random
    numbers generated by async_generator
    """
    return [i async for i in async_generator()]
